# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 89a16c5e5a283435ca1647837de6f01ea79a985a62bc01f4530c7a79321f39de591a3e04b21f906f9b35ee98d1528e416d21db4a0b6e701ce7d99ad8095888e5

test:
  secret_key_base: 99f81228f20546598018b0e8c56773008f45019ec379a6b2353c6b3f5621fac80de110cbc6800054f6cf90b21f9dea057868a727e783474e42b36d631fae6da0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
